enum LocalStorageKeys {
    TOP_HEADLINES = "TOP_HEADLINES",
    TOP_HEADLINES_CHANGED = "TOP_HEADLINES_CHANGED",
    CURRENT_HEADLINES_MAX_INDEX = "CURRENT_HEADLINES_MAX_INDEX",
    TOP_HEADLINES_PAGE = "TOP_HEADLINES_PAGE",
    TOP_HEADLINES_PINNED_LIST = "TOP_HEADLINES_PINNED_LIST"
}

export default LocalStorageKeys